export ZSH="/Users/rafamedina/.oh-my-zsh"
# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="agnoster"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)

DISABLE_UPDATE_PROMPT=true

plugins=(osx git git-extras themes vagrant brew node npm python sublime cp docker gitignore git-prompt)

source $ZSH/oh-my-zsh.sh
prompt_context() {
  if [[ "$USER" != "$DEFAULT_USER" || -n "$SSH_CLIENT" ]]; then
    prompt_segment purple default "%(!.%{%F{yellow}%}.)"
  fi
}

function preexec() {
  timer=$(($(print -P %D{%s%6.})/1000))
}

function _command_time_precmd() {
  if [ $timer ]; then
    now=$(($(print -P %D{%s%6.})/1000))
    elapsed=$(($now-$timer))

    print ">> took ${elapsed}ms"
    unset timer
  fi
}
precmd_functions+=(_command_time_precmd)

# Customize to your needs...
# Aliases
alias dotfiles="cd ~/.dotfiles"
alias vi="nvim"
alias vim="nvim"
alias vimrc="vim ~/.vimrc"
alias zshrc="vim ~/.zshrc"
alias reload="source ~/.zshrc"
alias tempshot="sudo powermetrics --samplers smc -i1 -n1"
alias temp="sudo powermetrics|grep -i \"temperature\""

alias run-lint="~/.dotfiles/commands/lint.sh"

# Enable Colors
export CLICOLOR=1;
export LSCOLORS=exfxcxdxbxegedabagacad;

export DOCKER_HOST=tcp://127.0.0.1:2375
export PATH=/usr/local/bin:/usr/local/sbin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH
export GOPATH=$HOME/gocode
export GOROOT=/usr/local/opt/go/libexec
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$GOROOT/bin
export EDITOR=/usr/bin/vim
export GOPATH=$HOME/gocode
fpath=($HOME/.zsh/func $fpath)
typeset -U fpath


# Enable Colors
export CLICOLOR=1;
export LSCOLORS=exfxcxdxbxegedabagacad;

export PATH=/usr/local/bin:/usr/local/sbin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH
export EDITOR="/usr/local/bin/vim"
export PAGER="/usr/local/bin/most"
export GIT_PAGER="/usr/bin/less"

# Locale
export LANG="en_US.UTF-8"
export LC_COLLATE="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export LC_MESSAGES="en_US.UTF-8"
export LC_MONETARY="en_US.UTF-8"
export LC_NUMERIC="en_US.UTF-8"
export LC_TIME="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# source "`brew --prefix grc`/etc/grc.bashrc"


# eval "$(rbenv init -)"

export GPG_TTY=$(tty)
export PINENTRY_USER_DATA="USE_CURSES=1"


unset DOCKER_TLS_VERIFY
unset DOCKER_CERT_PATH
unset DOCKER_MACHINE_NAME
unset DOCKER_HOST

# eval "$(jenv init -)"

alias python=/usr/bin/python3
